# Generated by Django 4.1.2 on 2022-10-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tags_job_skills_intern_skills'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Skills',
        ),
    ]
