# Generated by Django 4.1.2 on 2022-11-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_intern_coding_intern_marketing_skills_and_more'),
        ('users', '0002_rename_tag_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('preference', models.IntegerField(default=1)),
                ('intern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.intern')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job')),
            ],
        ),
    ]
