# Generated by Django 4.1.2 on 2022-11-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_internpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internpreference',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='internpreference',
            name='job',
        ),
    ]
