# Generated by Django 4.1.2 on 2022-11-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_intern_coding_intern_marketing_skills_and_more'),
        ('users', '0004_remove_internpreference_intern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internpreference',
            name='intern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.intern'),
        ),
        migrations.AddField(
            model_name='internpreference',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job'),
        ),
    ]
