# Generated by Django 4.1.2 on 2022-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_internpreference_intern_internpreference_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internpreference',
            name='preference',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
