# Generated by Django 4.1.2 on 2022-11-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_intern_coding_intern_marketing_skills_and_more'),
        ('users', '0006_alter_internpreference_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internpreference',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job'),
        ),
        migrations.AlterField(
            model_name='internpreference',
            name='preference',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
