# Generated by Django 4.1.2 on 2022-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_intern_skills_remove_job_skills'),
        ('users', '0007_alter_internpreference_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterField(
            model_name='internpreference',
            name='preference',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
