# Generated by Django 4.1.2 on 2022-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_skills_alter_internpreference_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internpreference',
            name='preference',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
    ]
