# Generated by Django 4.1.2 on 2022-11-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_internpreference_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internpreference',
            name='preference',
            field=models.IntegerField(blank=True),
        ),
    ]
