image: python:latest

variables:
  PROJECT_DIR: "gradRotate" # location of settings.py
  #assumption- PROJECT_DIR is also the name of the manage.py location
  DOMAIN: "masterclass.bham.team" # the DNS A record must point to the ip of $UBUNTU_SERVER... need to see this
  EMAIL: "admin@$DOMAIN"

test:
  before_script:
    - pip install -r requirements.txt -v # install required pip packages
    - python3 manage.py collectstatic --settings=gradRotate.local --noinput 
    - python3 manage.py makemigrations accounts --settings=gradRotate.local --noinput 
    - python3 manage.py makemigrations users --settings=gradRotate.local --noinput 
    - python3 manage.py makemigrations dashboard --settings=gradRotate.local --noinput 
    - python3 manage.py makemigrations interface --settings=gradRotate.local --noinput 
    - python3 manage.py migrate --settings=gradRotate.local --noinput 
    - python3 manage.py createsuperuser --noinput --username admin --email $EMAIL --settings=gradRotate.local
  script:
    - echo "run the tests here"

artifact:
  script:
    - echo "creating artifact"    
  artifacts:
    name: "SuperDjangoCICD"
    paths:
      - $CI_PROJECT_DIR
    exclude:
      - $CI_PROJECT_DIR/deploy/*

deploy:
  before_script:
    - 'command -v ssh-agent >/dev/null || (apt install -y openssh)' 
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add 
    - echo "Host $UBUNTU_SERVER" >> ~/.ssh/config
    - echo "    StrictHostKeyChecking no" >> ~/.ssh/config
    - chmod 400 ~/.ssh/config
    - ssh root@$UBUNTU_SERVER "ufw allow ssh"
    #postgres
    - ssh root@$UBUNTU_SERVER "pg_isready -h localhost -p 5432 || (apt update && apt install -y postgresql postgresql-contrib && service postgresql restart)"
    - apt update && apt install -y gettext-base
    - envsubst < deploy/db.template > deploy/db.create.script
    - scp deploy/db.create.script root@$UBUNTU_SERVER:/tmp/db.create.script
    - ssh root@$UBUNTU_SERVER "cd /tmp && sudo -u postgres psql -f /tmp/db.create.script"
  script:
    - echo "hello, deploy"