# Generated by Django 4.1.2 on 2022-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('accounts', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(to='users.tag'),
        ),
    ]
