# Generated by Django 4.1.2 on 2022-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0004_intern_user_job_user_alter_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='tags',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='intern',
            name='skills',
            field=models.ManyToManyField(to='users.tag'),
        ),
    ]
