# Generated by Django 4.1.2 on 2022-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tags_job_skills_intern_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='coding',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intern',
            name='marketing_skills',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intern',
            name='project_management',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intern',
            name='web_skills',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='job',
            name='coding',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='job',
            name='marketing_skills',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='job',
            name='project_management',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='job',
            name='web_skills',
            field=models.IntegerField(default=5),
        ),
    ]
