# Generated by Django 4.1.2 on 2022-11-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_intern_coding_intern_marketing_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
