# Generated by Django 4.1.2 on 2022-11-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_intern_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
