# Generated by Django 4.1.2 on 2022-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_job_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
