# Generated by Django 4.1.2 on 2022-11-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='first_preference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='second_preference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='third_preference',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
