# Generated by Django 4.1.2 on 2022-11-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_intern_first_preference_intern_second_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='first_preference',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='second_preference',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='third_preference',
        ),
    ]
