# Generated by Django 4.1.2 on 2022-11-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
