# Generated by Django 4.1.2 on 2022-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_admin_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phase',
            field=models.CharField(choices=[('Job creation', 'Job creation'), ('Intern collection', 'Intern collection'), ('Allocate', 'Allocation')], max_length=200, null=True),
        ),
    ]
