# Generated by Django 4.1.2 on 2022-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_admin_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(choices=[('Newbury', 'Newbury'), ('London Paddington', 'London Paddington'), ('Speechmark', 'Speechmark')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='remote',
            field=models.CharField(choices=[('Everyday', 'Everyday'), ('3-4', '3-4'), ('1-2', '1-2'), ('Remote', 'Remote')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phase',
            field=models.CharField(choices=[('Job creation', 'Job creation'), ('Intern collection', 'Intern collection'), ('Allocation', 'Allocation')], max_length=200, null=True),
        ),
    ]
