# Generated by Django 4.1.2 on 2022-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='skills',
            field=models.ManyToManyField(to='accounts.skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='accounts.skills'),
        ),
    ]
