# Generated by Django 4.1.2 on 2022-11-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_skills_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
    ]
