# Generated by Django 4.1.2 on 2022-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_skills_computingskills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='intern',
            name='admin_skills',
            field=models.ManyToManyField(to='accounts.adminskills'),
        ),
        migrations.AddField(
            model_name='intern',
            name='analytic_skills',
            field=models.ManyToManyField(to='accounts.analyticskills'),
        ),
        migrations.AddField(
            model_name='intern',
            name='business_skills',
            field=models.ManyToManyField(to='accounts.businessskills'),
        ),
        migrations.AddField(
            model_name='intern',
            name='leadership_skills',
            field=models.ManyToManyField(to='accounts.leadershipskills'),
        ),
        migrations.AddField(
            model_name='intern',
            name='management_skills',
            field=models.ManyToManyField(to='accounts.managementskills'),
        ),
        migrations.AddField(
            model_name='job',
            name='admin_skills',
            field=models.ManyToManyField(to='accounts.adminskills'),
        ),
        migrations.AddField(
            model_name='job',
            name='analytic_skills',
            field=models.ManyToManyField(to='accounts.analyticskills'),
        ),
        migrations.AddField(
            model_name='job',
            name='business_skills',
            field=models.ManyToManyField(to='accounts.businessskills'),
        ),
        migrations.AddField(
            model_name='job',
            name='leadership_skills',
            field=models.ManyToManyField(to='accounts.leadershipskills'),
        ),
        migrations.AddField(
            model_name='job',
            name='management_skills',
            field=models.ManyToManyField(to='accounts.managementskills'),
        ),
    ]
