# Generated by Django 4.1.2 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_intern_marketing1_skills_job_marketing1_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('Everyday', 'Everyday'), ('3-4', '3-4'), ('1-2', '1-2'), ('Remote', 'Remote')], max_length=200, null=True),
        ),
    ]
