# Generated by Django 4.1.2 on 2022-11-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_job_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='wage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='wage',
            field=models.IntegerField(default=0),
        ),
    ]
