# Generated by Django 4.1.2 on 2022-11-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_intern_wage_job_wage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='marketing1_skills',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='project_management',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='web_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='job',
            name='marketing1_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='project_management',
        ),
        migrations.RemoveField(
            model_name='job',
            name='web_skills',
        ),
    ]
