# Generated by Django 4.1.2 on 2022-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_intern_coding_remove_intern_marketing1_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='daily_tasks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
