# Generated by Django 4.1.2 on 2022-12-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_job_daily_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='wage',
        ),
    ]
