# Generated by Django 4.1.2 on 2022-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_intern_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='intern',
            name='job_location',
            field=models.ManyToManyField(to='accounts.joblocation'),
        ),
    ]
