# Generated by Django 4.1.2 on 2022-12-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_joblocation_intern_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='job_location',
        ),
        migrations.AddField(
            model_name='intern',
            name='job_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.joblocation'),
            preserve_default=False,
        ),
    ]
