# Generated by Django 4.1.2 on 2022-12-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_intern_job_location_alter_intern_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='location',
            new_name='job_location',
        ),
    ]
