# Generated by Django 4.1.2 on 2022-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_location_intern_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(choices=[('Newbury', 'Newbury'), ('London Paddington', 'London Paddington'), ('Speechmark', 'Speechmark')], max_length=200, null=True),
        ),
    ]
