# Generated by Django 4.1.2 on 2022-12-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_intern_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.joblocation'),
        ),
    ]
