# Generated by Django 4.1.2 on 2022-12-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_intern_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='location',
        ),
    ]
