# Generated by Django 4.1.2 on 2022-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_joblocation_latitude_joblocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
