# Generated by Django 4.1.2 on 2022-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_intern_team_alter_job_wage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='team',
        ),
        migrations.AddField(
            model_name='job',
            name='team',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
