# Generated by Django 4.1.2 on 2022-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_intern_team_job_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
