# Generated by Django 4.1.2 on 2022-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_admin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='date',
            new_name='allocation_creation_date',
        ),
        migrations.AddField(
            model_name='admin',
            name='intern_creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='job_creation_date',
            field=models.DateField(null=True),
        ),
    ]
