# Generated by Django 4.1.2 on 2022-12-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_date_admin_allocation_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='automate_phase',
            field=models.BooleanField(default=False),
        ),
    ]
