# Generated by Django 4.1.2 on 2023-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_admin_automate_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='total_interns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
