# Generated by Django 4.1.2 on 2023-01-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_intern_allocated_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allocated_intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.intern'),
        ),
    ]
