# Generated by Django 4.1.2 on 2023-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_manager_job_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
