# Generated by Django 4.1.2 on 2023-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_remove_manager_email_remove_manager_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='allocation_algorithm',
            field=models.CharField(choices=[('Job creation', 'Job creation'), ('Intern collection', 'Intern collection'), ('Allocation', 'Allocation')], max_length=200, null=True),
        ),
    ]
